### ISSUE TITLE
Add snackbar notification for signup / signin procedure

### ISSUE THREAD

**Issue by S0YKIM** [innohack2021/python-hitchhiker#1]
sokim @S0YKIM 

- [x] 회원가입 성공 알림
- [x] 로그인 실패 알림
- [x]  snackbar notification 기능 이해하고 활용하기

**Comment by S0YKIM** [comment]
로그인 실패 알림만 뜨고 회원가입 성공 알림이 안 뜹니다.

**Comment by swkim12345** [comment]
회원가입성공 알림 배경이 진주색이라 잘 안보이는 거 같네요. 검은색으로 롤백해서 올리도록 하겠습니다.
