### ISSUE TITLE
Basic UX/UI implementations

### ISSUE THREAD

**Issue by S0YKIM** [innohack2021/python-hitchhiker#3]
### Login

- [x]  Signup / Signin 버튼 디자인  @swkim12345 
- [x] Profile 눌렀을 때에 Signout 이 분리되는 현상 @jujinesy

### Logo and Footer
- [x]  Logo 이미지로 만들거나 CSS 로 꾸미기  @swkim12345 
- [x]  Footer 디자인 개선  @jujinesy 

### Progress bar
- [x] progress bar 디자인 개선  @ft-jasong

**Comment by jujinesy** [comment]
풀리퀘 완료!

**Comment by jujinesy** [comment]
#23

**Comment by swkim12345** [comment]
signup/sigin in 버튼 디자인만 이슈 분리했습니다.
이 이슈는 종료하도록 하겠습니다.
